library(readxl)
library(dplyr)
library(tidyverse)
library(tidyr)

loc_drill <- read_csv("Add Date/location_drillhole_HYNY_T1NY_T3XV.csv",
                      col_names=c("drillhole","date","block","easting","northing",
                      "elev","x","y","z"))
HY_geo    <- read_csv("Add Date/HGBN_block.csv")
HY_geo    <- select(HY_geo, "No","Block","E/W","N/S","ELEV")
HY_geo    <- mutate(HY_geo, No = str_replace(No, "_H15", "HYNY"))
HY_geo    <- mutate(HY_geo, numb=str_extract_all(No,"[0-9]{1,}"))
HY_geo    <- mutate(HY_geo, No = str_replace(No, "_C", "HYYB"))
HY_geo    <- mutate(HY_geo, No = str_replace(No, "_H", "HYYB"))
HY_geo    <- mutate(HY_geo, numb=str_pad(numb, 4, side ="left", pad="0"))
HY_geo    <- mutate(HY_geo, No=str_extract_all(No,"[A-Za-z]{1,}"))
HY_geo    <- unite(HY_geo, drillhole, No, numb, sep="")
HY_date   <- read_csv("Add Date/HGBN Dates.csv", col_names=c("drillhole","date"))
HY_date   <- mutate(HY_date, drillhole = str_replace(drillhole, "_H15", "HYNY"))
HY_date   <- mutate(HY_date, numb = str_extract_all(drillhole,"[0-9]{1,}"))
HY_date   <- mutate(HY_date, numb = str_pad(numb, 4, side ="left", pad="0"))
HY_date   <- mutate(HY_date, drillhole = "HYNY")
HY_date   <- unite(HY_date,drillhole,drillhole,numb, sep="")
HY_date   <- separate(HY_date, date, into=c("date","month","year"),sep="-")
HY_date   <- mutate(HY_date, year="2015")
HY_date   <- mutate(HY_date, month=match(HY_date$month,month.abb))
HY_date   <- mutate(HY_date, month = str_pad(month, 2, side ="left", pad="0"))
HY_date   <- mutate(HY_date, date = str_pad(date, 2, side ="left", pad="0"))
HY_date   <- unite(HY_date, date, year, month, date, sep="-")
loc_HY    <- left_join(loc_drill,HY_date, by="drillhole")
loc_HY    <- unite(loc_HY, date, date.x,date.y, sep="", na.rm = TRUE)
loc_HY    <- left_join(loc_HY,HY_geo, by="drillhole")
loc_HY    <- unite(loc_HY, block, block, Block, sep="", na.rm = TRUE)
loc_HY    <- unite(loc_HY, easting, easting, "E/W", sep="", na.rm = TRUE)
loc_HY    <- unite(loc_HY, northing, northing, "N/S", sep="", na.rm = TRUE)
loc_HY    <- unite(loc_HY, elev, elev, ELEV, sep="", na.rm = TRUE)


